version: "2.1"
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  test-and-build:
    docker:
      - image: "cimg/node:18.4.0-browsers"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test:ci
      - run: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build
  s3-deployment:
    docker:
      - image: "cimg/node:18.4.0-browsers"
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: build
          to: "s3://demo-ci-cd-app/"
workflows:
  build-and-deploy:
    jobs:
      - test-and-build
      - s3-deployment:
          requires:
            - test-and-build
          filters:
            branches:
              only: main
